server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&autoConnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: false
    test-while-idle: true
    max-conn-lifetime-millis: 3600000
  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis
    redis:
      flush-mode: on_save
    timeout: 30m
  mail:
    host: smtp.163.com
    port: 465
    username: 13212792230@163.com
    password: 163email
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: noreply@techblog.com
      mail.display.sendname: noreply
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  task:
    scheduling:
      pool:
        size: 20
      thread-name-prefix: Job-Thread-



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zhumingbei.techblog.bean
## 监控管理
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

file:
  static-access-path: /static/images/**

###文件上传
upload:
  url-prefix: http://localhost:8888/static
  static-access-path: /static/**
  root: /Users/fadedfat3/Pictures/techblog/upload/  #必须/结尾，表明为目录
  file: file
  avatar: avatar
  image: image
url:
  ignore:
    get:
      - "/user/email/activate"
    post:
      - "/registry"
      - "/login"
    pattern:
      - "/error"
      - "/static/**"
      - "/user/password/getVerifyCode"
      - "/user/password/reset"
      - "/user/*/article/show/*"
      - "/user/*/article/index"
##jwt
jwt:
  config:
    key: fadedfate
    ttl:   86400 #s, 1 day
    remember: 604800 #记住我，7天有效期;小于0为永远记住
    redis-key-prefix: jwt.
##日志
logging:
  file: logs/app.log
  level:
    com:
      zhumingbei:
        techblog: debug
    org:
      springframework:
        web: debug
        security: DEBUG
        session: debug
    root: WARN


