server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&autoConnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    test-on-borrow: false
    test-while-idle: true
    max-conn-lifetime-millis: 3600000

  mail:
    host: smtp.163.com
    port: 465
    username: 13212792230@163.com
    password: 163email
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: noreply@techblog.com
      mail.display.sendname: noreply
  task:
    scheduling:
      pool:
        size: 20
      thread-name-prefix: Job-Thread-



## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
## 监控管理
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


###文件上传
upload:
  path: uploads

url:
  ignore:
    get:
      - "/api/auth/login"
    post:
      - "/auth/login"
      - "/auth/registry"
    pattern:
      - "/test/*"

##jwt
jwt:
  config:
    key: fadedfate
    ttl:   86400 #s, 1 day
    remember: 604800 #记住我，7天有效期;小于0为永远记住
    redis-key-prefix: jwt.
##日志
logging:
  file: logs/app.log
  level:
    com:
      zhumingbei:
        techblog: INFO
    org:
      springframework:
        web: INFO
        security: INFO
    root: WARN


